"""LLM prompt templates."""

SECTION_CLASSIFY_SYSTEM = """You are a QA automation expert classifying DOM elements into page sections.
Assign each element to exactly one section: Header, Navigation, MainContent, Sidebar, Form, Modal, Footer, or Other.
Use element tag, text, aria-label, dom_path, and role to decide."""

SECTION_CLASSIFY_USER = """Page: {page_title}
URL: {url}

Classify each element into a section.

Elements:
{elements_json}

Return JSON with assignments array containing element_id and section for every element."""

XPATH_GENERATE_SYSTEM = """You are a senior test automation engineer generating stable XPath locators for UI test automation.
Rules:
1. Prefer attribute-based XPaths: id, data-testid, aria-label, name, href, placeholder, then link/button text.
2. Use //tag[@attr='value'] form — absolute /html/body paths are OK but attribute selectors are preferred.
3. Never use auto-generated React/Vue IDs like :r0: or random hashes.
4. Avoid bare //tag or (//tag)[1] — every XPath must uniquely identify ONE element.
5. For text matching use normalize-space() and keep strings short; use contains() for long text.
6. element_name must be PascalCase and describe the user action (e.g. LoginButton, EmailInput, NavPricingLink).
7. confidence: high if unique id/testid, medium if aria/name/text-based, low if positional/contains-based.
8. Skip decorative or duplicate elements — each locator must target a distinct actionable UI control."""

XPATH_GENERATE_USER = """Page: {page_title}
URL: {url}

Generate XPath locators for these elements:

{elements_json}

Return JSON with locators array containing element_id, element_name, xpath, confidence, rationale."""

XPATH_REPAIR_SYSTEM = """You are fixing a failed XPath locator for test automation.

The XPath failed cross-browser validation. Provide a revised XPath from /html/body.

Follow these rules:
- Prefer stable attributes such as id, data-testid, aria-label, and name.
- Avoid unstable autogenerated IDs and React-generated IDs.
- Use stable DOM structure when reliable attributes are unavailable.
- The repaired XPath must identify exactly one intended element.
- The repaired XPath should target the actual element described by the provided tag and text.
- Return the result as a valid JSON object.

The JSON object must contain exactly these fields:
- xpath: the corrected XPath string
- confidence: one of "high", "medium", or "low"
- rationale: a brief explanation of why the XPath was corrected

Do not return Markdown or code fences. Return only the JSON object."""


XPATH_REPAIR_USER = """Page: {page_title}
Element: {element_name}
Tag: {tag}
Text: {text}
Failed XPath: {failed_xpath}
DOM path hint: {dom_path}
Validation error: {error}

Return a valid JSON object with the corrected xpath, confidence, and rationale."""

